import { ConversationMode } from '../types';

export const conversationModes: ConversationMode[] = [
  {
    id: 'job-interview',
    name: 'Job Interview',
    description: 'Practice common interview questions and scenarios',
    icon: 'briefcase',
    systemPrompt: 'You are a professional interviewer conducting a job interview. Ask relevant questions and provide constructive feedback.',
    category: 'interview',
    difficulty: 'intermediate',
    estimatedDuration: 15,
  },
  {
    id: 'presentation-practice',
    name: 'Presentation Practice',
    description: 'Improve your public speaking and presentation skills',
    icon: 'presentation',
    systemPrompt: 'You are an experienced presentation coach. Help the user practice their presentation skills with constructive feedback.',
    category: 'presentation',
    difficulty: 'intermediate',
    estimatedDuration: 20,
  },
  {
    id: 'casual-conversation',
    name: 'Casual Chat',
    description: 'Have a relaxed conversation on any topic',
    icon: 'message-circle',
    systemPrompt: 'You are a friendly conversation partner. Engage in natural, flowing conversation on various topics.',
    category: 'casual',
    difficulty: 'beginner',
    estimatedDuration: 10,
  },
  {
    id: 'business-meeting',
    name: 'Business Meeting',
    description: 'Practice professional communication and negotiation',
    icon: 'users',
    systemPrompt: 'You are a business professional in a meeting. Engage in professional discussions and business scenarios.',
    category: 'business',
    difficulty: 'advanced',
    estimatedDuration: 25,
  },
  {
    id: 'language-learning',
    name: 'Language Practice',
    description: 'Practice pronunciation and conversation skills',
    icon: 'globe',
    systemPrompt: 'You are a language tutor. Help the user practice their speaking skills with patience and encouragement.',
    category: 'learning',
    difficulty: 'beginner',
    estimatedDuration: 15,
  },
  {
    id: 'confidence-building',
    name: 'Confidence Building',
    description: 'Build speaking confidence in a supportive environment',
    icon: 'heart',
    systemPrompt: 'You are a supportive coach focused on building speaking confidence. Provide encouragement and positive reinforcement.',
    category: 'learning',
    difficulty: 'beginner',
    estimatedDuration: 12,
  },
];